services:
  db:
    image: postgres:15
    container_name: messenger_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=messages_db
    ports:
      - "5432:5432"
    networks:
      - messenger_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  app:
    build: .
    container_name: messenger_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: messages_db
      APP_PORT: "8080"
    ports:
      - "8080:8080"
    networks:
      - messenger_net

networks:
  messenger_net:
    driver: bridge
