basePath: /
definitions:
  handlers.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  handlers.SendMessageRequest:
    properties:
      sequence:
        type: integer
      text:
        type: string
    type: object
  models.Message:
    properties:
      created_at:
        type: string
      id:
        type: integer
      sequence:
        type: integer
      text:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: developer@example.com
    name: Developer
    url: https://example.com
  description: Это приложение для обмена сообщениями.
  title: Chat Gopher API
  version: "1.0"
paths:
  /api/messages:
    get:
      consumes:
      - application/json
      description: Возвращает список сообщений из БД за указанный период
      parameters:
      - description: Начальная дата (RFC3339)
        in: query
        name: from
        required: true
        type: string
      - description: Конечная дата (RFC3339)
        in: query
        name: to
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Message'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Получить список сообщений за диапазон дат
      tags:
      - messages
    post:
      consumes:
      - application/json
      description: Создает новое сообщение, записывает в БД и рассылает его через
        WebSocket
      parameters:
      - description: Тело запроса
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.SendMessageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Отправить одно сообщение
      tags:
      - messages
schemes:
- http
swagger: "2.0"
